config/routes.rb
Pourover::Application.routes.draw do
  resources :consumptions
  resources :drinks
  devise_for :users

  root :to => 'consumptions#index'
  get '/preferences', to: 'static#preferences'
  get '/api/consumptions/heatmap', to: 'consumptions#heatmap'
end

app/models/consumption.rb
class Consumption < ActiveRecord::Base
  attr_accessible :consumed_at, :drink_id, :user_id, :image_url, :street_address,
    :latitide, :longitude

  belongs_to :drink
  belongs_to :user

  geocoded_by :street_address
  after_validation :geocode
end

app/models/drink.rb
class Drink < ActiveRecord::Base
  attr_accessible :caffeine, :description, :image_url, :name

  belongs_to :consumption
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name

  has_many :consumptions

  def short_name
    name.split(' ').first
  end

  # lol we'll hold this off till later
  def heatmap?
    return false
    email == 'colby@aley.me'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def authenticate
    redirect_to new_user_session_path unless current_user
  end

end

app/controllers/consumptions_controller.rb
class ConsumptionsController < ApplicationController
  before_filter :authenticate

  # GET /consumptions
  # GET /consumptions.json
  def index
    @consumptions = current_user.consumptions.order('created_at DESC')
    @today        = @consumptions.where('consumed_at >= ?', Time.zone.now.beginning_of_day)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @consumptions }
    end
  end

  # GET /consumptions/1
  # GET /consumptions/1.json
  def show
    @consumption = Consumption.find(params[:id])
    redirect_to root_path unless @consumption.user_id == current_user.id

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @consumption }
    end
  end

  def heatmap
    hash = Hash.new
    consumptions = current_user.consumptions
    (14.days.ago.to_date).upto(Date.today).each do |date|
      count = consumptions.select{|c| c.consumed_at.to_date == date }.size
      hash.merge!(date.to_time.utc.to_i => count)
    end

    render json: hash
  end

  # GET /consumptions/new
  # GET /consumptions/new.json
  def new
    @consumption = Consumption.new
    @drinks = Drink.all.map { |d| [d.name, d.id.to_s ] }
    @default_drink = 0

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @consumption }
    end
  end

  # GET /consumptions/1/edit
  def edit
    @consumption = Consumption.find(params[:id])
    @drinks = Drink.all.map { |d| [d.name, d.id.to_s ] }
    @default_drink = @consumption.drink.id
  end

  # POST /consumptions
  # POST /consumptions.json
  def create
    @consumption = Consumption.new(params[:consumption])
    @consumption.drink_id = params[:drink_id].to_i
    @consumption.user_id = current_user.id

    respond_to do |format|
      if @consumption.save
        format.html { redirect_to @consumption, notice: 'Saved!' }
        format.json { render json: @consumption, status: :created, location: @consumption }
      else
        format.html { render action: "new" }
        format.json { render json: @consumption.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /consumptions/1
  # PUT /consumptions/1.json
  def update
    @consumption = Consumption.find(params[:id])

    respond_to do |format|
      if @consumption.update_attributes(params[:consumption])
        format.html { redirect_to @consumption, notice: 'Consumption was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @consumption.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consumptions/1
  # DELETE /consumptions/1.json
  def destroy
    @consumption = Consumption.find(params[:id])
    @consumption.destroy

    respond_to do |format|
      format.html { redirect_to consumptions_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  # GET /drinks
  # GET /drinks.json
  def index
    @drinks = Drink.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @drinks }
    end
  end

  # GET /drinks/1
  # GET /drinks/1.json
  def show
    @drink = Drink.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @drink }
    end
  end

  # GET /drinks/new
  # GET /drinks/new.json
  def new
    @drink = Drink.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @drink }
    end
  end

  # GET /drinks/1/edit
  def edit
    @drink = Drink.find(params[:id])
  end

  # POST /drinks
  # POST /drinks.json
  def create
    @drink = Drink.new(params[:drink])

    respond_to do |format|
      if @drink.save
        format.html { redirect_to @drink, notice: 'Drink was successfully created.' }
        format.json { render json: @drink, status: :created, location: @drink }
      else
        format.html { render action: "new" }
        format.json { render json: @drink.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /drinks/1
  # PUT /drinks/1.json
  def update
    @drink = Drink.find(params[:id])

    respond_to do |format|
      if @drink.update_attributes(params[:drink])
        format.html { redirect_to @drink, notice: 'Drink was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @drink.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drinks/1
  # DELETE /drinks/1.json
  def destroy
    @drink = Drink.find(params[:id])
    @drink.destroy

    respond_to do |format|
      format.html { redirect_to drinks_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def index
  end

  # This really needs to be put somewhere else.
  def preferences
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consumptions_helper.rb
module ConsumptionsHelper

  def caffeine(consumptions)
    caffeine = 0
    consumptions.each do |c|
      caffeine += c.drink.caffeine
    end
    caffeine
  end

  def map_url(consumptions)
    url = "http://maps.google.com/maps/api/staticmap?size=550x350&sensor=false"
    consumptions.each do |c|
      next unless c.geocoded?
      url << "&markers=#{c.latitude},#{c.longitude}"
    end
    url
  end
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/consumptions/_form.html.erb
<%= form_for(@consumption) do |f| %>
  <% if @consumption.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@consumption.errors.count, "error") %> prohibited this consumption from being saved:</h2>

      <ul>
      <% @consumption.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="form-table">
    <tr>
      <td><%= f.label :drink %></td>
      <td><%= select_tag :drink_id, options_for_select(@drinks, selected: @default_drink), prompt: 'Select a drink' %></td>
    </tr>
    <tr>
      <td><%= f.label :when %></td>
      <td><%= f.datetime_select :consumed_at, default: Time.now %></td>
    </tr>
    <tr>
      <td><%= f.label :street_address %></td>
      <td><%= f.text_field :street_address %></td>
    </tr>
    <tr>
      <td><%= f.label :image_url, 'Image' %></td>
      <td><%= f.filepicker_field :image_url, class: 'btn btn-default' %></td>
    </tr>
  </table>
  <div class="actions">
    <%= f.submit class: 'btn btn-default save', value: 'Save' %>
  </div>
</table>

<% end %>

app/views/consumptions/_heatmap.erb
<div class="panel panel-default heatmap">
  <div class="panel-heading">Heatmap</div>
  <div class="panel-body">
    <div id="cal-heatmap"></div>
    <script type="text/javascript">
      var cal = new CalHeatMap();
      cal.init({
        domain: "day",
        range: 14,
        start: new Date(new Date().setDate(new Date().getDate()-13)),
        cellSize: 12,
        legend: [2, 4, 8, 10],
        itemName: ["coffee consumption", "coffee consumptions"],
        data: "/api/consumptions/heatmap"
      });
    </script>
  </div>
</div>

app/views/consumptions/edit.html.erb
<%= render 'form' %>

app/views/consumptions/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Log</div>
  <div class="panel-body">
    <table class="table">
      <tr>
        <th>Drink</th>
        <th>Consumed</th>
        <th>Caffeine</th>
        <th></th>
        <th></th>
      </tr>

    <% @consumptions.each do |consumption| %>
      <tr>
        <td><%= consumption.drink.name %></td>
        <td><%= consumption.consumed_at.strftime('%b %e %Y %H:%M %p') %></td>
        <td><%= consumption.drink.caffeine %> mg</td>
        <td><%= link_to 'View', consumption %></td>
        <td><%= image_tag 'camera.svg', class: 'light-icon', 'data-toggle' => :tooltip, title: 'This consumption has a photo.' unless consumption.image_url.empty? %>
            <%= image_tag 'map.svg', class: 'light-icon', 'data-toggle' => :tooltip, title: 'This consumption has a location.' if consumption.geocoded? %>
        </td>
      </tr>
    <% end %>
    </table>
  </div>
</div>

<div class="panel panel-default home map">
  <div class="panel-heading">Map</div>
  <div class="panel-body">
    <% if Consumption.all.map(&:geocoded?).include?(true) %>
      <%= image_tag map_url(@consumptions), class: 'map' %>
    <% else %>
      Add a location to one of your recordings!
    <% end %>
  </div>
</div>

<div class="panel panel-default home stats">
  <div class="panel-heading">Stats</div>
  <div class="panel-body">
    <table class="table">
      <tr>
        <td><strong>Recorded Consumptions:</strong></td>
        <td><%= @consumptions.count %></td>
      </tr>
      <tr>
        <td><strong>Consumptions today:</strong></td>
        <td><%= @today.count %></td>
      </tr>
      <tr>
        <td><strong>Consumptions this month:</strong></td>
        <td><%= @consumptions.where('consumed_at >= ?', 1.month.ago).count %></td>
      </tr>
      <tr>
        <td><strong>Consumptions this week:</strong></td>
        <td><%= @consumptions.where('consumed_at >= ?', 1.week.ago).count %></td>
      </tr>
      <tr>
        <td><strong>Caffeine today (mg):</strong></td>
        <td><%= caffeine(@today) %></td>
      </tr>
    </table>
  </div>
</div>

<%= render 'heatmap' if current_user.heatmap? %>
<br>

app/views/consumptions/new.html.erb
<h2>Record</h2>

<%= render 'form' %>

app/views/consumptions/show.html.erb
<p><strong><%= @consumption.drink.name %>, <%= time_ago_in_words @consumption.consumed_at %> ago, <%= @consumption.consumed_at.strftime('%b %e %Y %H:%m %p') %>.</strong></p>

Recorded: <%= @consumption.created_at.strftime('%b %e %Y %H:%M %p') %>
<br>
<%= filepicker_image_tag(@consumption.image_url, w: 320) unless @consumption.image_url.empty? %>

<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=18&center=#{@consumption.latitude},#{@consumption.longitude}&markers=#{@consumption.latitude},#{@consumption.longitude}" if @consumption.geocoded? %>

<br>
<%= link_to 'Edit', edit_consumption_path(@consumption) %>

app/views/drinks/_form.html.erb
<%= form_for(@drink) do |f| %>
  <% if @drink.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@drink.errors.count, "error") %> prohibited this drink from being saved:</h2>

      <ul>
      <% @drink.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :caffeine %><br />
    <%= f.number_field :caffeine %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/drinks/edit.html.erb
<h1>Editing drink</h1>

<%= render 'form' %>

<%= link_to 'Show', @drink %> |
<%= link_to 'Back', drinks_path %>

app/views/drinks/index.html.erb
<h1>Listing drinks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Caffeine</th>
    <th>Description</th>
    <th>Image url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @drinks.each do |drink| %>
  <tr>
    <td><%= drink.name %></td>
    <td><%= drink.caffeine %></td>
    <td><%= drink.description %></td>
    <td><%= drink.image_url %></td>
    <td><%= link_to 'Show', drink %></td>
    <td><%= link_to 'Edit', edit_drink_path(drink) %></td>
    <td><%= link_to 'Destroy', drink, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Drink', new_drink_path %>

app/views/drinks/new.html.erb
<h1>New drink</h1>

<%= render 'form' %>

<%= link_to 'Back', drinks_path %>

app/views/drinks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @drink.name %>
</p>

<p>
  <b>Caffeine:</b>
  <%= @drink.caffeine %>
</p>

<p>
  <b>Description:</b>
  <%= @drink.description %>
</p>

<p>
  <b>Image url:</b>
  <%= @drink.image_url %>
</p>


<%= link_to 'Edit', edit_drink_path(@drink) %> |
<%= link_to 'Back', drinks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pourover</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= filepicker_js_include_tag %>
  <%= csrf_meta_tags %>
  <script type="text/javascript" src="//d3js.org/d3.v3.min.js"></script>
  <script type="text/javascript" src="//cdn.jsdelivr.net/cal-heatmap/3.3.10/cal-heatmap.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="//cdn.jsdelivr.net/cal-heatmap/3.3.10/cal-heatmap.css" />
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <%= link_to 'Pourover', root_path, class: 'navbar-brand' %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li><%= button_to 'Record', new_consumption_path, method: :get, type: 'button', class: 'btn btn-default navbar-btn' %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.short_name %> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Preferences', preferences_path %></li>
                <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Log in', new_user_session_path %></li>
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container page">
    <%= yield %>
    <footer>
      <hr>
      Pourover
    </footer>
  </div>

</body>
</html>